### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by AndyHeinz** [moritzj29/tonie_sync#1]
Hi,
I unfortunatelly can't get the docker up and running. After I build the Image and gonna start docker-compose it fails:

Creating TonieboxSync ... done
Attaching to TonieboxSync
TonieboxSync    | Traceback (most recent call last):
TonieboxSync    |   File "/tonie/tonie_sync/start.py", line 11, in <module>
TonieboxSync    |     from tonie_sync import TonieSpotifySync
TonieboxSync    |   File "/tonie/tonie_sync/tonie_sync/__init__.py", line 1, in <module>
TonieboxSync    |     from .sync import *
TonieboxSync    |   File "/tonie/tonie_sync/tonie_sync/sync.py", line 7, in <module>
TonieboxSync    |     from spotdl.command_line.core import Spotdl
TonieboxSync    | ModuleNotFoundError: No module named 'spotdl.command_line'
TonieboxSync exited with code 1

How Do I get this running? 
Thanks!

**Comment by heilmic** [comment]
I get the same errors. Any updates availables?

I am searching for a way to sync tonies with spotify...

**Comment by moritzj29** [comment]
Hi, thanks for your interest in this project! Actually, I have never really used this code, since I found that the content I was interested in, was not reliably downloaded by `Spotdl` (mostly audiobooks for children, which are simply not available on youtube...). `Spotdl` went through a lot of rebranding and recoding, and also some legal issues I guess, so the `Spotdl` related code for sure needs some updates.

Have you checked @rado0x54 fork of the project? It looks like he did some adjustments to keep spotify working: https://github.com/rado0x54/tonie_sync

**Comment by moritzj29** [comment]
and of course the original project which inspired me:
https://github.com/maximilianvoss/musicsync
it is actively maintained and uses a different (more robust) approach for downloading tracks. It appears to be available as docker now as well!

I think I will archive this repo for now... feel free to fork!
